# Generated by Django 3.2.12 on 2022-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=100)),
                ("is_etf", models.BooleanField(default=0)),
            ],
        ),
    ]
